### ISSUE TITLE
simplify fs code: 

### ISSUE THREAD

**Issue by rshade** [sous-chefs/filesystem#27]
@coderanger said: shell_out('mount', '-o', "remount,#{fields[3]}", mount, returns: [MOUNT_EX_FAIL]).error? to simplify code

**Comment by damacus** [comment]
I think the code is simplified now?

**Comment by MarkGibbons** [comment]
shell_out('mount', '-o', "remount,#{fields[3]}", mount, returns: [MOUNT_EX_FAIL]).error?
will treat a return code of 0 or FAIL as an indication that the file system is frozen, that test is unfortunately incorrect. A zero return should indicate that the file system is not frozen.   On some of the tested systems a condition of busy o returns a code of 1 instead of FAIL which would indicate that the file system is frozen.

**Comment by rshade** [comment]
@MarkGibbons I didn't get a chance to test it. I am not sure the changes in the last 3 years, I would close it.

**Comment by MarkGibbons** [comment]
I'm adding some missing tests and cleaning up a little, it's a small change. Just dumped some notes here in case I get interrupted.

**Comment by MarkGibbons** [comment]
Fixed by #88
